from dotenv import load_dotenv
import os

load_dotenv()

# Minio
MINIO_ACCESS_KEY=os.getenv("MINIO_ACCESS_KEY", None)
MINIO_SECRET_KEY=os.getenv("MINIO_SECRET_KEY", None)

# Kafka
KAFKA_TOPIC=os.getenv("KAFKA_TOPIC", None)
BUCKET_NAME_RAW=os.getenv("BUCKET_NAME_RAW", None)
BUCKET_NAME_OCR=os.getenv("BUCKET_NAME_OCR", None)
NAMESPACE=os.getenv("NAMESPACE", None)
MINIO_ENDPOINT=os.getenv("MINIO_ENDPOINT", None)
KAFKA_HOST=os.getenv("KAFKA_HOST", None)

# OpenAI
OPENAI_API_KEY=os.getenv("OPENAI_API_KEY", None)

# Pinecone
PINECONE_API_KEY=os.getenv("PINECONE_API_KEY", None)
PINECONE_INDEX_NAME=os.getenv("PINECONE_INDEX_NAME", None)
PINECONE_ENVIRONMENT=os.getenv("PINECONE_ENVIRONMENT", None)

# Google authentication
GOOGLE_CREDENTIALS_TYPE=os.getenv("GOOGLE_CREDENTIALS_TYPE", None)
GOOGLE_CLIENT_X509_CERT_URL=os.getenv("GOOGLE_CLIENT_X509_CERT_URL", None)
GOOGLE_PROJECT_ID=os.getenv("GOOGLE_PROJECT_ID", None)
GOOGLE_PRIVATE_KEY_ID=os.getenv("GOOGLE_PRIVATE_KEY_ID", None)
GOOGLE_PRIVATE_KEY=os.getenv("GOOGLE_PRIVATE_KEY", None)
GOOGLE_CLIENT_EMAIL=os.getenv("GOOGLE_CLIENT_EMAIL", None)
GOOGLE_CLIENT_ID=os.getenv("GOOGLE_CLIENT_ID", None)
GOOGLE_UNIVERSE_DOMAIN=os.getenv("GOOGLE_UNIVERSE_DOMAIN", None)

# Google cloud document ai
OCR_RECOMMEND_PROCESSOR_ID=os.getenv("OCR_RECOMMEND_PROCESSOR_ID", None)
OCR_OTHER_PROCESSOR_ID=os.getenv("OCR_OTHER_PROCESSOR_ID", None)
CLASSIFICATION_PROCESSOR_ID=os.getenv("CLASSIFICATION_PROCESSOR_ID", None)
CLASSIFICATION_PROCESSOR_VERSION_ID=os.getenv("CLASSIFICATION_PROCESSOR_VERSION_ID", None)
SUMMARIZATION_PROCESSOR_ID=os.getenv("SUMMARIZATION_PROCESSOR_ID", None)

# Google cloud generative language
GEMINI_API_KEY=os.getenv("GEMINI_API_KEY", None)
GEMINI_MODEL=os.getenv("GEMINI_MODEL", "gemini-1.5-flash:002")
